package c.smartdisaster.networkingfinal;

import java.util.Comparator;

public class Job { // Jobs are generated by devices and travel through the netwrok
    int id; // the ID of the Job
    int priority; // the priority of the job
    int progress; // the amount of bits currently  transferred/computed
    int totalPayLoad; // the total size of the job

    float computeTime;
    float networkTime;
    float time;

    String deviceOrigin;
    String location; // the current location of the job | channel_1, Local Center, Remote Center etc
    String state; // the current state of the job | waiting, transferring, computing, completed
    Channel channel;

    Job (int i, int p, int size, String loc) { //  location initialized with device job started at
        id = i;
        priority = p;
        time = 0;
        computeTime = 0;
        networkTime = 0;
        progress = 0;
        totalPayLoad = size;
        location = loc;
        deviceOrigin = loc;
        state = "waiting"; // Jobs always start as waiting
        channel = null;
    }

    float GetProgress () { // gets the progress of the job transmission/computation
        return (float) progress / totalPayLoad * 100;
    }

}

class JobComparator implements Comparator<Job> {
    public int compare(Job j1, Job j2) {
        if (j1.priority > j2.priority)
            return 1;
        else if (j1.priority < j2.priority)
            return -1;
        return 0;
    }
}

